orbs:
  slack: circleci/slack@5.2.3
  cypress: cypress-io/cypress@5.0.1
version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: shotaromatsuya/fbj:20
  slack-executor:
    docker:
      - image: 'cibuilds/base:latest'
    resource_class: small
environment:
  TZ: '/usr/share/zoneinfo/Asia/Tokyo'
  NODE_ENV: 'development'
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
            - npm-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: npm-{{ checksum "package-lock.json" }}
  linting:
    executor: default
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
            - npm-
      - run:
          name: Run linting
          command: npm run lint
  prettier:
    executor: default
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
            - npm-
      - run:
          name: Run prettier check
          command: npm run prettier:check
  test:
    executor: default
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
            - npm-
      - run:
          name: Run Component Test
          command: npm run test:unit
  deploy:
    executor: default
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Build Project
          command: |
            npm install
            npm run build
            cd dist
            zip ../dist.zpi -r * .[^.]*
            echo "Build successful"
      - run:
          name: Deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=${FIREBASE_TOKEN}
  notify-via-slack:
    executor: slack-executor
    steps:
      - run: echo "Slack notification"
      - slack/notify:
          event: 'always'
          channel: C02R8V82XDH
          template: 'success_tagged_deploy_1'

workflows:
  build-and-deploy:
    jobs:
      - build
      - linting:
          requires:
            - build
      - prettier:
          requires:
            - build
      - test:
          requires:
            - linting
            - prettier
      - cypress/run:
          filters:
            branches:
              only: main
          cypress-command: npx wait-on@latest http://localhost:8080 && npx cypress run --parallel --record
          start-command: npm run serve
          parallelism: 2
      - deploy:
          requires:
            - test
            - cypress/run
          filters:
            branches:
              only: main
      - notify-via-slack:
          requires:
            - deploy
          filters:
            branches:
              only: main
