version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ai-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17dag1qbzov3x"
s3_prefix = "ai-backend"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ArticleTableName=\"Articles\" Region=\"ap-northeast-1\" S3BucketName=\"smat710-polly-output\""
image_repositories = []
