version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "scraping-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17dag1qbzov3x"
s3_prefix = "scraping-api"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ScrapingTableName=\"Scrapings\" ArticleTableName=\"Articles\" Region=\"ap-northeast-1\" EMAIL=\"matsuya@h01.itscom.net\""
image_repositories = []
